In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('cik_ticker.csv', sep='|')

In [4]:
df.head()

,CIK,Ticker,Name,Exchange,SIC,Business,Incorporated,IRS
0,1090872,A,Agilent Technologies Inc,NYSE,3825.0,CA,DE,770518772.0
1,4281,AA,Alcoa Inc,NYSE,3350.0,PA,PA,250317820.0
2,1332552,AAACU,Asia Automotive Acquisition Corp,NaN,6770.0,DE,DE,203022522.0
3,1287145,AABB,Asia Broadband Inc,OTC,8200.0,GA,NV,721569126.0
4,1024015,AABC,Access Anytime Bancorp Inc,NaN,6035.0,NM,DE,850444597.0

In [5]:
df.Exchange = df.Exchange.astype(str)

In [6]:
df.shape

(13737, 8)

In [7]:
df = df[(df['Exchange'] == 'NYSE') | (df['Exchange'] == 'NASDAQ')]

In [8]:
df.shape

(5549, 8)

In [9]:
df.drop(columns=['Business', 'Incorporated', 'IRS'], inplace=True)

In [10]:
df = df.reset_index(drop=True)

In [11]:
df.head()

,CIK,Ticker,Name,Exchange,SIC
0,1090872,A,Agilent Technologies Inc,NYSE,3825.0
1,4281,AA,Alcoa Inc,NYSE,3350.0
2,1099290,AAC,Sinocoking Coal & Coke Chemical Industries Inc,NASDAQ,3312.0
3,6201,AAL,American Airlines Group Inc,NASDAQ,4512.0
4,8177,AAME,Atlantic American Corp,NASDAQ,6311.0

In [12]:
df.CIK = df.CIK.astype(str)

In [13]:
df['CIK'] = df['CIK'].str.zfill(10)

In [14]:
df.head(30)

,CIK,Ticker,Name,Exchange,SIC
0,0001090872,A,Agilent Technologies Inc,NYSE,3825.0
1,0000004281,AA,Alcoa Inc,NYSE,3350.0
2,0001099290,AAC,Sinocoking Coal & Coke Chemical Industries Inc,NASDAQ,3312.0
3,0000006201,AAL,American Airlines Group Inc,NASDAQ,4512.0
4,0000008177,AAME,Atlantic American Corp,NASDAQ,6311.0
5,0000706688,AAN,Aarons Inc,NYSE,7359.0
6,0001158114,AAOI,Applied Optoelectronics Inc,NASDAQ,3674.0
7,0000824142,AAON,Aaon Inc,NASDAQ,3585.0
8,0001158449,AAP,Advance Auto Parts Inc,NYSE,5531.0
9,0000320193,AAPL,Apple Inc,NASDAQ,3571.0
10,0001500217,AAT,American Assets Trust Inc,NYSE,6798.0
11,0000801558,AB,Cannon Express Inc,NYSE,4213.0
12,0000825313,AB,Alliancebernstein Holding LP,NYSE,6282.0
13,0000881890,ABAX,Abaxis Inc,NASDAQ,3829.0
14,0001551152,ABBV,Abbvie Inc,NYSE,2834.0
15,0001140859,ABC,Amerisourcebergen Corp,NYSE,5122.0
16,0000351569,ABCB,Ameris Bancorp,NASDAQ,6022.0
17,0001466815,ABCD,Cambium Learning Group Inc,NASDAQ,2741.0
18,0001157377,ABCO,Advisory Board Co,NASDAQ,8741.0
19,0000841071,ABER,Dominion Diamond Corp,NYSE,1000.0
20,0000894405,ABFS,Arkansas Best Corp,NASDAQ,4213.0
21,0001144980,ABG,Asbury Automotive Group Inc,NYSE,5500.0
22,0001393066,ABH,Resolute Forest Products Inc,NYSE,2621.0
23,0001409012,ABII,Abraxis Bioscience Inc,NASDAQ,2834.0
24,0000874501,ABK,Ambac Financial Group Inc,NASDAQ,6351.0
25,0000771497,ABM,Abm Industries Inc,NYSE,7340.0
26,0000815094,ABMD,Abiomed Inc,NASDAQ,3841.0
27,0001253986,ABR,Arbor Realty Trust Inc,NYSE,6798.0
28,0000003333,ABS,Albertsons Inc,NYSE,5411.0
29,0000001800,ABT,Abbott Laboratories,NYSE,2834.0

In [22]:
#Try number 2
df[df['CIK']=='0000861361']
df2 = df[df.index>560]
df2.head()

            CIK Ticker                            Name Exchange     SIC
561  0000861361   BEAV                               B   NASDAQ  2531.0
562  0001059272   BEBE                 Bebe Stores Inc   NASDAQ  2330.0
563  0001124941   BECN       Beacon Roofing Supply Inc   NASDAQ  5030.0
564  0000910079    BED  Bedford Property Investors Inc     NYSE  6798.0
565  0001057436    BEE  Strategic Hotels & Resorts Inc     NYSE  6798.0

In [27]:
#Try number 3
df2[df2['CIK']=='0000009092']
df3 = df2[df2.index>662]
df3.head()

            CIK Ticker                           Name Exchange     SIC
663  0000009092    BMI               Badger Meter Inc     NYSE  3824.0
664  0001275477    BMM  Bimini Capital Management Inc     NYSE  6798.0
665  0001307579   BMOM      Liqtech International Inc     NYSE  3590.0
666  0001289236    BMR        Biomed Realty Trust Inc     NYSE  6798.0
667  0001403475   BMRC          Bank Of Marin Bancorp   NASDAQ  6022.0

In [32]:
#Try number 4
df3[df3['CIK']=='0000831001']
df4 = df3[df3.index>783]
df4.head()

            CIK Ticker                          Name Exchange     SIC
784  0000831001      C                 Citigroup Inc     NYSE  6021.0
785  0000356028     CA                        Ca Inc   NASDAQ  7372.0
786  0001157762   CAAS  China Automotive Systems Inc   NASDAQ  3714.0
787  0001267130    CAB                   Cabelas Inc     NYSE  5940.0
788  0000750686    CAC          Camden National Corp   NASDAQ  6021.0

In [15]:
from sec_edgar_downloader import Downloader
dl = Downloader('data/')

In [34]:
for i in df4.index:
    dl.get("8-K", df4.CIK[i], after_date="20030101", include_amends=True)

KeyboardInterrupt:

136624 8-ks, 1838 Companys, 82 gig